# Generated by Django 5.0.4 on 2024-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('assignee', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('todo', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_repeat', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
