# Generated by Django 5.0.4 on 2024-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReminderSync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('assignee', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('repeat', models.CharField(max_length=10)),
                ('completed', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CSVData',
        ),
    ]
